# Generated by Django 4.0.4 on 2022-06-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_article_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(blank=True, max_length=9000),
        ),
    ]
